from Node import Node
from Graph import Graph

def initStations(g, stations):
    nodes = [
        Node("Redfern", stations['Redfern']),
        Node("Central", stations['Central']),
        Node("Town Hall", stations['Town Hall']),
        Node("Wynyard", stations['Wynyard']),
        Node("Circular Quay", stations['Circular Quay']),
        Node("St James", stations['St James']),
        Node("Museum", stations['Museum']),
        Node("Normanhurst", stations['Normanhurst']),
        Node("Thornleigh", stations['Thornleigh']),
        Node("Pennant Hills", stations['Pennant Hills']),
        Node("Beecroft", stations['Beecroft']),
        Node("Cheltenham", stations['Cheltenham']),
        Node("Epping", stations['Epping']),
        Node("Eastwood", stations['Eastwood']),
        Node("Denistone", stations['Denistone']),
        Node("West Ryde", stations['West Ryde']),
        Node("Meadowbank", stations['Meadowbank']),
        Node("Rhodes", stations['Rhodes']),
        Node("Concord West", stations['Concord West']),
        Node("North Strathfield", stations['North Strathfield']),
        Node("Macarthur", stations['Macarthur']),
        Node("Campbelltown", stations['Campbelltown']),
        Node("Leumeah", stations['Leumeah']),
        Node("Minto", stations['Minto']),
        Node("Ingleburn", stations['Ingleburn']),
        Node("Macquarie Fields", stations['Macquarie Fields']),
        Node("Glenfield", stations['Glenfield']),
        Node("Holsworthy", stations['Holsworthy']),
        Node("East Hills", stations['East Hills']),
        Node("Panania", stations['Panania']),
        Node("Revesby", stations['Revesby']),
        Node("Padstow", stations['Padstow']),
        Node("Riverwood", stations['Riverwood']),
        Node("Narwee", stations['Narwee']),
        Node("Beverly Hills", stations['Beverly Hills']),
        Node("Kingsgrove", stations['Kingsgrove']),
        Node("Bexley North", stations['Bexley North']),
        Node("Bardwell Park", stations['Bardwell Park']),
        Node("Turrella", stations['Turrella']),
        Node("Tempe", stations['Tempe']),
        Node("St Peters", stations['St Peters']),
        Node("Ersineville", stations['Ersineville']),
        Node("Green Square", stations['Green Square']),
        Node("Mascot", stations['Mascot']),
        Node("Domestic", stations['Domestic']),
        Node("International", stations['International']),
        Node("Wolli", stations['Wolli']),
        Node("Olympic Park", stations['Olympic Park']),
        Node("Lidcombe", stations['Lidcombe']),
        Node("Carlingford", stations['Carlingford']),
        Node("Telopea", stations['Telopea']),
        Node("Dundas", stations['Dundas']),
        Node("Rydalmere", stations['Rydalmere']),
        Node("Camellia", stations['Camellia']),
        Node("Rosehill", stations['Rosehill']),
        Node("Clyde", stations['Clyde']),
        Node("Richmond", stations['Richmond']),
        Node("East Richmond", stations['East Richmond']),
        Node("Clarendon", stations['Clarendon']),
        Node("Windsor", stations['Windsor']),
        Node("Mulgrave", stations['Mulgrave']),
        Node("Vineyard", stations['Vineyard']),
        Node("Riverstone", stations['Riverstone']),
        Node("Schofields", stations['Schofields']),
        Node("Quakers Hill", stations['Quakers Hill']),
        Node("Marayong", stations['Marayong']),
        Node("Blacktown", stations['Blacktown']),
        Node("Seven Hills", stations['Seven Hills']),
        Node("Toongabbie", stations['Toongabbie']),
        Node("Pendle Hill", stations['Pendle Hill']),
        Node("Wentworthville", stations['Wentworthville']),
        Node("Westmead", stations['Westmead']),
        Node("Parramatta", stations['Parramatta']),
        Node("Harris Park", stations['Harris Park']),
        Node("Merrylands", stations['Merrylands']),
        Node("Guildford", stations['Guildford']),
        Node("Yennora", stations['Yennora']),
        Node("Fairfield", stations['Fairfield']),
        Node("Canley Vale", stations['Canley Vale']),
        Node("Cabramatta", stations['Cabramatta']),
        Node("Warwick Farm", stations['Warwick Farm']),
        Node("Liverpool", stations['Liverpool']),
        Node("Casula", stations['Casula']),
        Node("Glenfield", stations['Glenfield']),
        Node("Edmondson Park", stations['Edmondson Park']),
        Node("Leppington", stations['Leppingon']),
        Node("Bondi Junction", stations['Bondi Junction']),
        Node("Edgecliff", stations['Edgecliff']),
        Node("Kings Cross", stations['Kings Cross']),
        Node("Martin Place", stations['Martin Place']),
        Node("Arncliffe", stations['Arncliffe']),
        Node("Banksia", stations['Banksia']),
        Node("Rockdale", stations['Rockdale']),
        Node("Kogarah", stations['Kogarah']),
        Node("Carlton", stations['Carlton']),
        Node("Allawah", stations['Allawah']),
        Node("Hurstville", stations['Hurstville']),
        Node("Penshurst", stations['Penshurst']),
        Node("Mortdale", stations['Mortdale']),
        Node("Oatley", stations['Oatley']),
        Node("Como", stations['Como']),
        Node("Jannali", stations['Jannali']),
        Node("Sutherland", stations['Sutherland']),
        Node("Loftus", stations['Loftus']),
        Node("Engadine", stations['Engadine']),
        Node("Heathcote", stations['Heathcote']),
        Node("Waterfall", stations['Waterfall']),
        Node("Carramar", stations['Carramar']),
        Node("Villawood", stations['Villawood']),
        Node("Leightonfield", stations['Leightonfield']),
        Node("Chester Hill", stations['Chester Hil']),
        Node("Sefton", stations['Sefton']),
        Node("Birrong", stations['Birrong']),
        Node("Yagoona", stations['Yagoona']),
        Node("Bankstown", stations['Bankstown']),
        Node("Punchbowl", stations['Punchbowl']),
        Node("Wiley Park", stations['Wiley Park']),
        Node("Lakemba", stations['Lakemba']),
        Node("Belmore", stations['Belmore']),
        Node("Campsie", stations['Campsie']),
        Node("Canterbury", stations['Canterbury']),
        Node("Hurlstone Park", stations['Hurlstone Park']),
        Node("Dulwich Hill", stations['Dulwich Hill']),
        Node("Marrickville", stations['Marrickville']),
        Node("Lidcombe", stations['Lidcombe']),
        Node("Berala", stations['Berala']),
        Node("Regents Park", stations['Regents Park']),
        Node("Parramatta", stations['Parramatta']),
        Node("Harris Park", stations['Harris Park']),
        Node("Granville", stations['Granville']),
        Node("Clyde", stations['Clyde']),
        Node("Auburn", stations['Auburn']),
        Node("Lidcombe", stations['Lidcombe']),
        Node("Burwood", stations['Burwood']),
        Node("Croydon", stations['Croydon']),
        Node("Ashfield", stations['Ashfield']),
        Node("Summer Hill", stations['Summer Hill']),
        Node("Lewisham", stations['Lewisham']),
        Node("Petersham", stations['Petersham']),
        Node("Stanmore", stations['Stanmore']),
        Node("Newtown", stations['Newtown']),
        Node("Macdonaldtown", stations['Macdonaldtown']),
        Node("Berowra", stations['Berowra']),
        Node("Mount Kurring-gai", stations['Mount Kurring-gai']),
        Node("Mount Colah", stations['Mount Colah']),
        Node("Asquith", stations['Asquith']),
        Node("Hornsby", stations['Hornsby']),
        Node("Waitara", stations['Waitara']),
        Node("Wahroonga", stations['Wahroonga']),
        Node("Warrawee", stations['Warrawee']),
        Node("Turramurra", stations['Turramurra']),
        Node("Pymble", stations['Pymble']),
        Node("Gordon", stations['Gordon']),
        Node("Killara", stations['Killara']),
        Node("Lindfield", stations['Lindfield']),
        Node("Roseville", stations['Roseville']),
        Node("Chatswood", stations['Chatswood']),
        Node("Artarmon", stations['Artarmon']),
        Node("St Leonards", stations['St Leonards']),
        Node("Wollstonecraft", stations['Wollstonecraft']),
        Node("Waverton", stations['Waverton']),
        Node("North Sydney", stations['North Sydney']),
        Node("Doonside", stations['Doonside']),
        Node("Rooty Hill", stations['Rooty Hill']),
        Node("Mount Druitt", stations['Mount Druitt']),
        Node("St Marys", stations['St Marys']),
        Node("Werrington", stations['Werrington']),
        Node("Kingswood", stations['Kingswood']),
        Node("Penrith", stations['Penrith']),
        Node("Emu Plains", stations['Emu Plains']),
        Node("Tallawong", stations['Tallawong']),
        Node("Rouse Hill", stations['Rouse Hill']),
        Node("Kellyville", stations['Kellyville']),
        Node("Bella Vista", stations['Bella Vista']),
        Node("Norwest", stations['Norwest']),
        Node("Hills Showground", stations['Hills Showground']),
        Node("Castle Hill", stations['Castle Hill']),
        Node("Cherrybrook", stations['Cherrybrook']),
        Node("Epping", stations['Epping']),
        Node("Macquarie University", stations['Macquarie University']),
        Node("Macquarie Park", stations['Macquarie Park']),
        Node("North Ryde", stations['North Ryde']),
        Node("Chatswood", stations['Chatswood']),
        Node("Milsons Point", stations['Milsons Point'])
    ]

    for n in nodes:
        g.addNode(n)