from Node import Node
from Graph import Graph

def initGraphStations(g, stations):
    """
    Adds nodes to a graph
    """
    for name, location in stations.items():
        node = Node(name, location)
        g.addNode(node)

# Returns a list of station dictionary entailing "name" - string, "location" - (latitude, longitude) for db schema
def initDbStations(stations):
    """
    Creates a list 
    """
    nodes = [
       {"name" : "Redfern", "location" : stations['Redfern']},
       {"name" : "Central", "location" : stations['Central']},
       {"name" : "Town Hall", "location" : stations['Town Hall']},
       {"name" : "Wynyard", "location" : stations['Wynyard']},
       {"name" : "Circular Quay", "location" : stations['Circular Quay']},
       {"name" : "St James", "location" : stations['St James']},
       {"name" : "Museum", "location" : stations['Museum']},
       {"name" : "Normanhurst", "location" : stations['Normanhurst']},
       {"name" : "Thornleigh", "location" : stations['Thornleigh']},
       {"name" : "Pennant Hills", "location" : stations['Pennant Hills']},
       {"name" : "Beecroft", "location" : stations['Beecroft']},
       {"name" : "Cheltenham", "location" : stations['Cheltenham']},
       {"name" : "Epping", "location" : stations['Epping']},
       {"name" : "Eastwood", "location" : stations['Eastwood']},
       {"name" : "Denistone", "location" : stations['Denistone']},
       {"name" : "West Ryde", "location" : stations['West Ryde']},
       {"name" : "Meadowbank", "location" : stations['Meadowbank']},
       {"name" : "Rhodes", "location" : stations['Rhodes']},
       {"name" : "Concord West", "location" : stations['Concord West']},
       {"name" : "North Strathfield", "location" : stations['North Strathfield']},
       {"name" : "Macarthur", "location" : stations['Macarthur']},
       {"name" : "Campbelltown", "location" : stations['Campbelltown']},
       {"name" : "Leumeah", "location" : stations['Leumeah']},
       {"name" : "Minto", "location" : stations['Minto']},
       {"name" : "Ingleburn", "location" : stations['Ingleburn']},
       {"name" : "Macquarie Fields", "location" : stations['Macquarie Fields']},
       {"name" : "Glenfield", "location" : stations['Glenfield']},
       {"name" : "Holsworthy", "location" : stations['Holsworthy']},
       {"name" : "East Hills", "location" : stations['East Hills']},
       {"name" : "Panania", "location" : stations['Panania']},
       {"name" : "Revesby", "location" : stations['Revesby']},
       {"name" : "Padstow", "location" : stations['Padstow']},
       {"name" : "Riverwood", "location" : stations['Riverwood']},
       {"name" : "Narwee", "location" : stations['Narwee']},
       {"name" : "Beverly Hills", "location" : stations['Beverly Hills']},
       {"name" : "Kingsgrove", "location" : stations['Kingsgrove']},
       {"name" : "Bexley North", "location" : stations['Bexley North']},
       {"name" : "Bardwell Park", "location" : stations['Bardwell Park']},
       {"name" : "Turrella", "location" : stations['Turrella']},
       {"name" : "Tempe", "location" : stations['Tempe']},
       {"name" : "St Peters", "location" : stations['St Peters']},
       {"name" : "Ersineville", "location" : stations['Ersineville']},
       {"name" : "Green Square", "location" : stations['Green Square']},
       {"name" : "Mascot", "location" : stations['Mascot']},
       {"name" : "Domestic", "location" : stations['Domestic']},
       {"name" : "International", "location" : stations['International']},
       {"name" : "Wolli", "location" : stations['Wolli']},
       {"name" : "Olympic Park", "location" : stations['Olympic Park']},
       {"name" : "Lidcombe", "location" : stations['Lidcombe']},
       {"name" : "Carlingford", "location" : stations['Carlingford']},
       {"name" : "Telopea", "location" : stations['Telopea']},
       {"name" : "Dundas", "location" : stations['Dundas']},
       {"name" : "Rydalmere", "location" : stations['Rydalmere']},
       {"name" : "Camellia", "location" : stations['Camellia']},
       {"name" : "Rosehill", "location" : stations['Rosehill']},
       {"name" : "Clyde", "location" : stations['Clyde']},
       {"name" : "Richmond", "location" : stations['Richmond']},
       {"name" : "East Richmond", "location" : stations['East Richmond']},
       {"name" : "Clarendon", "location" : stations['Clarendon']},
       {"name" : "Windsor", "location" : stations['Windsor']},
       {"name" : "Mulgrave", "location" : stations['Mulgrave']},
       {"name" : "Vineyard", "location" : stations['Vineyard']},
       {"name" : "Riverstone", "location" : stations['Riverstone']},
       {"name" : "Schofields", "location" : stations['Schofields']},
       {"name" : "Quakers Hill", "location" : stations['Quakers Hill']},
       {"name" : "Marayong", "location" : stations['Marayong']},
       {"name" : "Blacktown", "location" : stations['Blacktown']},
       {"name" : "Seven Hills", "location" : stations['Seven Hills']},
       {"name" : "Toongabbie", "location" : stations['Toongabbie']},
       {"name" : "Pendle Hill", "location" : stations['Pendle Hill']},
       {"name" : "Wentworthville", "location" : stations['Wentworthville']},
       {"name" : "Westmead", "location" : stations['Westmead']},
       {"name" : "Parramatta", "location" : stations['Parramatta']},
       {"name" : "Harris Park", "location" : stations['Harris Park']},
       {"name" : "Merrylands", "location" : stations['Merrylands']},
       {"name" : "Guildford", "location" : stations['Guildford']},
       {"name" : "Yennora", "location" : stations['Yennora']},
       {"name" : "Fairfield", "location" : stations['Fairfield']},
       {"name" : "Canley Vale", "location" : stations['Canley Vale']},
       {"name" : "Cabramatta", "location" : stations['Cabramatta']},
       {"name" : "Warwick Farm", "location" : stations['Warwick Farm']},
       {"name" : "Liverpool", "location" : stations['Liverpool']},
       {"name" : "Casula", "location" : stations['Casula']},
       {"name" : "Glenfield", "location" : stations['Glenfield']},
       {"name" : "Edmondson Park", "location" : stations['Edmondson Park']},
       {"name" : "Leppington", "location" : stations['Leppingon']},
       {"name" : "Bondi Junction", "location" : stations['Bondi Junction']},
       {"name" : "Edgecliff", "location" : stations['Edgecliff']},
       {"name" : "Kings Cross", "location" : stations['Kings Cross']},
       {"name" : "Martin Place", "location" : stations['Martin Place']},
       {"name" : "Arncliffe", "location" : stations['Arncliffe']},
       {"name" : "Banksia", "location" : stations['Banksia']},
       {"name" : "Rockdale", "location" : stations['Rockdale']},
       {"name" : "Kogarah", "location" : stations['Kogarah']},
       {"name" : "Carlton", "location" : stations['Carlton']},
       {"name" : "Allawah", "location" : stations['Allawah']},
       {"name" : "Hurstville", "location" : stations['Hurstville']},
       {"name" : "Penshurst", "location" : stations['Penshurst']},
       {"name" : "Mortdale", "location" : stations['Mortdale']},
       {"name" : "Oatley", "location" : stations['Oatley']},
       {"name" : "Como", "location" : stations['Como']},
       {"name" : "Jannali", "location" : stations['Jannali']},
       {"name" : "Sutherland", "location" : stations['Sutherland']},
       {"name" : "Loftus", "location" : stations['Loftus']},
       {"name" : "Engadine", "location" : stations['Engadine']},
       {"name" : "Heathcote", "location" : stations['Heathcote']},
       {"name" : "Waterfall", "location" : stations['Waterfall']},
       {"name" : "Carramar", "location" : stations['Carramar']},
       {"name" : "Villawood", "location" : stations['Villawood']},
       {"name" : "Leightonfield", "location" : stations['Leightonfield']},
       {"name" : "Chester Hill", "location" : stations['Chester Hil']},
       {"name" : "Sefton", "location" : stations['Sefton']},
       {"name" : "Birrong", "location" : stations['Birrong']},
       {"name" : "Yagoona", "location" : stations['Yagoona']},
       {"name" : "Bankstown", "location" : stations['Bankstown']},
       {"name" : "Punchbowl", "location" : stations['Punchbowl']},
       {"name" : "Wiley Park", "location" : stations['Wiley Park']},
       {"name" : "Lakemba", "location" : stations['Lakemba']},
       {"name" : "Belmore", "location" : stations['Belmore']},
       {"name" : "Campsie", "location" : stations['Campsie']},
       {"name" : "Canterbury", "location" : stations['Canterbury']},
       {"name" : "Hurlstone Park", "location" : stations['Hurlstone Park']},
       {"name" : "Dulwich Hill", "location" : stations['Dulwich Hill']},
       {"name" : "Marrickville", "location" : stations['Marrickville']},
       {"name" : "Lidcombe", "location" : stations['Lidcombe']},
       {"name" : "Berala", "location" : stations['Berala']},
       {"name" : "Regents Park", "location" : stations['Regents Park']},
       {"name" : "Parramatta", "location" : stations['Parramatta']},
       {"name" : "Harris Park", "location" : stations['Harris Park']},
       {"name" : "Granville", "location" : stations['Granville']},
       {"name" : "Clyde", "location" : stations['Clyde']},
       {"name" : "Auburn", "location" : stations['Auburn']},
       {"name" : "Lidcombe", "location" : stations['Lidcombe']},
       {"name" : "Burwood", "location" : stations['Burwood']},
       {"name" : "Croydon", "location" : stations['Croydon']},
       {"name" : "Ashfield", "location" : stations['Ashfield']},
       {"name" : "Summer Hill", "location" : stations['Summer Hill']},
       {"name" : "Lewisham", "location" : stations['Lewisham']},
       {"name" : "Petersham", "location" : stations['Petersham']},
       {"name" : "Stanmore", "location" : stations['Stanmore']},
       {"name" : "Newtown", "location" : stations['Newtown']},
       {"name" : "Macdonaldtown", "location" : stations['Macdonaldtown']},
       {"name" : "Berowra", "location" : stations['Berowra']},
       {"name" : "Mount Kurring-gai", "location" : stations['Mount Kurring-gai']},
       {"name" : "Mount Colah", "location" : stations['Mount Colah']},
       {"name" : "Asquith", "location" : stations['Asquith']},
       {"name" : "Hornsby", "location" : stations['Hornsby']},
       {"name" : "Waitara", "location" : stations['Waitara']},
       {"name" : "Wahroonga", "location" : stations['Wahroonga']},
       {"name" : "Warrawee", "location" : stations['Warrawee']},
       {"name" : "Turramurra", "location" : stations['Turramurra']},
       {"name" : "Pymble", "location" : stations['Pymble']},
       {"name" : "Gordon", "location" : stations['Gordon']},
       {"name" : "Killara", "location" : stations['Killara']},
       {"name" : "Lindfield", "location" : stations['Lindfield']},
       {"name" : "Roseville", "location" : stations['Roseville']},
       {"name" : "Chatswood", "location" : stations['Chatswood']},
       {"name" : "Artarmon", "location" : stations['Artarmon']},
       {"name" : "St Leonards", "location" : stations['St Leonards']},
       {"name" : "Wollstonecraft", "location" : stations['Wollstonecraft']},
       {"name" : "Waverton", "location" : stations['Waverton']},
       {"name" : "North Sydney", "location" : stations['North Sydney']},
       {"name" : "Doonside", "location" : stations['Doonside']},
       {"name" : "Rooty Hill", "location" : stations['Rooty Hill']},
       {"name" : "Mount Druitt", "location" : stations['Mount Druitt']},
       {"name" : "St Marys", "location" : stations['St Marys']},
       {"name" : "Werrington", "location" : stations['Werrington']},
       {"name" : "Kingswood", "location" : stations['Kingswood']},
       {"name" : "Penrith", "location" : stations['Penrith']},
       {"name" : "Emu Plains", "location" : stations['Emu Plains']},
       {"name" : "Tallawong", "location" : stations['Tallawong']},
       {"name" : "Rouse Hill", "location" : stations['Rouse Hill']},
       {"name" : "Kellyville", "location" : stations['Kellyville']},
       {"name" : "Bella Vista", "location" : stations['Bella Vista']},
       {"name" : "Norwest", "location" : stations['Norwest']},
       {"name" : "Hills Showground", "location" : stations['Hills Showground']},
       {"name" : "Castle Hill", "location" : stations['Castle Hill']},
       {"name" : "Cherrybrook", "location" : stations['Cherrybrook']},
       {"name" : "Epping", "location" : stations['Epping']},
       {"name" : "Macquarie University", "location" : stations['Macquarie University']},
       {"name" : "Macquarie Park", "location" : stations['Macquarie Park']},
       {"name" : "North Ryde", "location" : stations['North Ryde']},
       {"name" : "Chatswood", "location" : stations['Chatswood']},
       {"name" : "Milsons Point", "location" : stations['Milsons Point']},
       {"name" : "Sydenham", "location" : stations['Sydenham']},
       {"name" : "Tempe", "location" : stations['Tempe']},
       {"name" : "Kirrawee", "location" : stations['Kirrawee']},
       {"name" : "Miranda", "location" : stations['Miranda']},
       {"name" : "Gymea", "location" : stations['Gymea']},
       {"name" : "Caringbah", "location" : stations['Caringbah']},
       {"name" : "Woolooware", "location" : stations['Woolooware']},
       {"name" : "Cronulla", "location" : stations['Cronulla']},
       {"name" : "Flemington", "location" : stations['Flemington']},
       {"name" : "Strathfield", "location" : stations['Strathfield']},
       {"name" : "Homebush", "location" : stations['Homebush']},
    ]

    return nodes


